/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg23;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author oneide
 */
public class CriadorTreinosFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CriadorTreinosFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pi1/macos-big-sur-resized.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("tela 1");
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(230, 130, 126, 22);

        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(40, 210, 120, 22);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("adicionar ao treino");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 110, 110, 16);

        jLabel2.setText("treino");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 40, 37, 16);

        jFormattedTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField5);
        jFormattedTextField5.setBounds(40, 60, 120, 22);

        jFormattedTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField6);
        jFormattedTextField6.setBounds(40, 90, 120, 22);

        jFormattedTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField7);
        jFormattedTextField7.setBounds(40, 180, 120, 22);

        jFormattedTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField8);
        jFormattedTextField8.setBounds(40, 120, 120, 22);

        jFormattedTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField9);
        jFormattedTextField9.setBounds(40, 150, 120, 22);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 170, 80, 23);

        jButton2.setBackground(new java.awt.Color(204, 0, 255));
        jButton2.setText("salvar treino");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 240, 100, 23);

        jButton4.setBackground(new java.awt.Color(255, 204, 0));
        jButton4.setText("limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(230, 170, 75, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pi1/macos-big-sur-resized.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-30, -10, 700, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed

    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField5ActionPerformed

    private void jFormattedTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField7ActionPerformed

    private void jFormattedTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField8ActionPerformed

    private void jFormattedTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField9ActionPerformed

    private void jFormattedTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String exercicio = jFormattedTextField1.getText();

if (exercicio.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Digite um exercício primeiro!", "Aviso", JOptionPane.WARNING_MESSAGE);
    return;
}

// Array com os campos de destino
JFormattedTextField[] campos = {
    jFormattedTextField5,
    jFormattedTextField6,
    jFormattedTextField8,
    jFormattedTextField9,
    jFormattedTextField7,
    jFormattedTextField2
    // Adicione mais se tiver
};
boolean adicionado = false;
for (JFormattedTextField campo : campos) {
    if (campo.getText().isEmpty()) {
        campo.setText(exercicio);
        adicionado = true;
        break;
    }
}

if (!adicionado) {
    JOptionPane.showMessageDialog(this, "Todos os campos já estão preenchidos!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
} else {
    jFormattedTextField1.setText(""); // limpa o campo de entrada
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                             // Lista dos seus JFormattedTextField
    JFormattedTextField[] campos = {
    jFormattedTextField5,
    jFormattedTextField6,
    jFormattedTextField8,
    jFormattedTextField9,
    jFormattedTextField7,
    jFormattedTextField2
    };

    int contador = 0;

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/GymMaster", "root", "777666");
        PreparedStatement stmt = conn.prepareStatement("INSERT INTO exercicios (nome) VALUES (?)");

        for (JFormattedTextField campo : campos) {
            String nomeExercicio = campo.getText().trim();
            if (!nomeExercicio.isEmpty()) {
                stmt.setString(1, nomeExercicio);
                stmt.executeUpdate();
                contador++;
            }
        }

        conn.close();

        if (contador > 0) {
            JOptionPane.showMessageDialog(null, contador + " exercício(s) salvo(s) com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum exercício preenchido!");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Erro ao salvar no banco: " + e.getMessage());
        salvarTreino();
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jFormattedTextField1.setText("");
         jFormattedTextField5.setText("");
    jFormattedTextField6.setText("");
    jFormattedTextField8.setText("");
    jFormattedTextField9.setText("");
    jFormattedTextField7.setText("");
    jFormattedTextField2.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriadorTreinosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriadorTreinosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriadorTreinosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriadorTreinosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriadorTreinosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void salvarTreino() {
    // Aqui você implementaria a lógica real de salvar os dados, por enquanto mostramos uma mensagem
    JOptionPane.showMessageDialog(this, "Treino salvo com sucesso!");
}

}